Repository Kiki1875b/sb01-hrbank-team7, pull requests merged in 2025-03, with the labels that each got.

#11 feat : Employee DTO 추가, Employee 엔티티 Setter 수정
  src/main/java/team7/hrbank/domain/employee/Employee.java
  src/main/java/team7/hrbank/domain/employee/dto/CursorPageResponseEmployeeDto.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeCreateRequest.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeDto.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeUpdateRequest.java
Labels: ✨ Feature

#5 [FEATURE] BackupHistory 엔티티 설계
  src/main/java/team7/hrbank/domain/backup/dto/BackupDto.java
  src/main/java/team7/hrbank/domain/backup/entity/Backup.java
  src/main/java/team7/hrbank/domain/backup/entity/BackupStatus.java
  src/main/resources/schema.sql
Labels: ✨ Feature

#13 [FEATURE] Employee Controller 설계
  src/main/java/team7/hrbank/domain/employee/Employee.java
  src/main/java/team7/hrbank/domain/employee/EmployeeController.java
  src/main/java/team7/hrbank/domain/employee/EmployeeStatus.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeCreateRequest.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeDto.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeUpdateRequest.java
Labels: ✨ Feature

#18 [FEATURE] : ChangeLog 엔티티 설계
  src/main/java/team7/hrbank/domain/change_log/dto/ChangeLogDto.java
  src/main/java/team7/hrbank/domain/change_log/dto/DiffDto.java
  src/main/java/team7/hrbank/domain/change_log/entity/ChangeLog.java
  src/main/java/team7/hrbank/domain/change_log/entity/ChangeLogType.java
Labels: ✨ Feature

#22 feat : Backup 도메인 컨트롤러, 서비스, 레포지토리 추가
  build.gradle
  src/main/java/team7/hrbank/common/config/QuerydslConfig.java
  src/main/java/team7/hrbank/common/dto/PageResponse.java
  src/main/java/team7/hrbank/domain/backup/controller/BackupController.java
  src/main/java/team7/hrbank/domain/backup/entity/Backup.java
  src/main/java/team7/hrbank/domain/backup/entity/BackupStatus.java
  src/main/java/team7/hrbank/domain/backup/exception/BackupException.java
  src/main/java/team7/hrbank/domain/backup/mapper/BackupMapper.java
  src/main/java/team7/hrbank/domain/backup/repository/BackupRepository.java
  src/main/java/team7/hrbank/domain/backup/repository/CustomBackupRepository.java
  src/main/java/team7/hrbank/domain/backup/repository/CustomBackupRepositoryImpl.java
  src/main/java/team7/hrbank/domain/backup/service/BackupService.java
  src/main/java/team7/hrbank/domain/backup/service/BackupServiceImpl.java
  src/main/resources/schema.sql
Labels: ✨ Feature

#25 [Refactoring] 파일 저장 및 조회 조건 수정(확장자 추가)
  build.gradle
  src/main/java/team7/hrbank/HrbankApplication.java
  src/main/java/team7/hrbank/domain/.gitkeep
  src/main/java/team7/hrbank/domain/base/BaseEntity.java
  src/main/java/team7/hrbank/domain/binary/BinaryContent.java
  src/main/java/team7/hrbank/domain/binary/BinaryContentRepository.java
  src/main/java/team7/hrbank/domain/binary/BinaryContentService.java
  src/main/java/team7/hrbank/domain/binary/BinaryController.java
  src/main/java/team7/hrbank/domain/binary/LocalBinaryContentStorage.java
  src/main/java/team7/hrbank/domain/binary/dto/BinaryContentDto.java
  src/main/java/team7/hrbank/domain/binary/dto/BinaryMapper.java
  src/main/resources/application.yml
  src/test/java/team7/hrbank/binary/basicBinary.java
Labels: 🔧 Refactor

#29 feat : optimized pagination logic and connected Backup to database
  .gitignore
  src/main/java/team7/hrbank/domain/backup/controller/BackupController.java
  src/main/java/team7/hrbank/domain/backup/dto/BackupDto.java
  src/main/java/team7/hrbank/domain/backup/entity/Backup.java
  src/main/java/team7/hrbank/domain/backup/repository/CustomBackupRepository.java
  src/main/java/team7/hrbank/domain/backup/service/BackupService.java
  src/main/java/team7/hrbank/domain/backup/service/BackupServiceImpl.java
  src/main/resources/schema.sql
Labels: ✨ Feature

#30 feat : ChangeLog 컨트롤러, 서비스, 레포지토리 생성
  src/main/java/team7/hrbank/domain/change_log/ChangeLogController.java
  src/main/java/team7/hrbank/domain/change_log/ChangeLogRepository.java
  src/main/java/team7/hrbank/domain/change_log/ChangeLogService.java
  src/main/java/team7/hrbank/domain/change_log/dto/ChangeLogDto.java
Labels: ✨ Feature

#32 [FEATURE] Employee Controller, Service, Repository 설계
  src/main/java/team7/hrbank/domain/base/BaseEntity.java
  src/main/java/team7/hrbank/domain/change_log/ChangeLogService.java
  src/main/java/team7/hrbank/domain/change_log/entity/ChangeLog.java
  src/main/java/team7/hrbank/domain/employee/EmployeeStatus.java
  src/main/java/team7/hrbank/domain/employee/controller/EmployeeController.java
  src/main/java/team7/hrbank/domain/employee/dto/CursorPageResponseEmployeeDto.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeDto.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeUpdateRequest.java
  src/main/java/team7/hrbank/domain/employee/entity/Employee.java
  src/main/java/team7/hrbank/domain/employee/entity/EmployeeStatus.java
  src/main/java/team7/hrbank/domain/employee/repository/CustomEmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/repository/CustomEmployeeRepositoryImpl.java
  src/main/java/team7/hrbank/domain/employee/repository/EmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeService.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeServiceImpl.java
Labels: ✨ Feature

#35 [REFACTOR] : 페이지네이션, 사원번호 생성 수정
  src/main/java/team7/hrbank/domain/employee/repository/CustomEmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/repository/CustomEmployeeRepositoryImpl.java
  src/main/java/team7/hrbank/domain/employee/repository/EmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeServiceImpl.java
Labels: 🔧 Refactor

#33 [FEATURE] : Backup 수행시 필요 없을 경우 일부 동작
  src/main/java/team7/hrbank/domain/backup/controller/BackupController.java
  src/main/java/team7/hrbank/domain/backup/dto/BackupListRequestDto.java
  src/main/java/team7/hrbank/domain/backup/entity/Backup.java
  src/main/java/team7/hrbank/domain/backup/repository/BackupRepository.java
  src/main/java/team7/hrbank/domain/backup/repository/CustomBackupRepository.java
  src/main/java/team7/hrbank/domain/backup/repository/CustomBackupRepositoryImpl.java
  src/main/java/team7/hrbank/domain/backup/service/BackupService.java
  src/main/java/team7/hrbank/domain/backup/service/BackupServiceImpl.java
  src/main/java/team7/hrbank/domain/change_log/ChangeLogRepository.java
  src/main/java/team7/hrbank/domain/change_log/ChangeLogService.java
  src/main/java/team7/hrbank/domain/change_log/entity/ChangeLog.java
Labels: ✨ Feature

#46 [REFACTOR] : ChangeLog 서비스, 레포지토리 패키지 생성 및 리펙토링
  src/main/java/team7/hrbank/domain/backup/service/BackupServiceImpl.java
  src/main/java/team7/hrbank/domain/change_log/ChangeLogRepository.java
  src/main/java/team7/hrbank/domain/change_log/controller/ChangeLogController.java
  src/main/java/team7/hrbank/domain/change_log/repository/ChangeLogRepository.java
  src/main/java/team7/hrbank/domain/change_log/repository/CustomChangeLogRepository.java
  src/main/java/team7/hrbank/domain/change_log/repository/CustomChangeLogRepositoryImpl.java
  src/main/java/team7/hrbank/domain/change_log/service/ChangeLogService.java
  src/main/java/team7/hrbank/domain/change_log/service/ChangeLogServiceImpl.java
Labels: 🔧 Refactor

#48 [FEATURE] : Backup Batch 처리
  .gitignore
  build.gradle
  src/main/java/team7/hrbank/common/extractor/EmployeeFieldExtractor.java
  src/main/java/team7/hrbank/config/BackupBatchConfig.java
  src/main/java/team7/hrbank/domain/backup/entity/Backup.java
  src/main/java/team7/hrbank/domain/backup/mapper/BackupMapper.java
  src/main/java/team7/hrbank/domain/backup/repository/BackupRepository.java
  src/main/java/team7/hrbank/domain/backup/service/BackupServiceImpl.java
  src/main/java/team7/hrbank/domain/binary/BinaryContentService.java
  src/main/java/team7/hrbank/domain/binary/LocalBinaryContentStorage.java
  src/main/java/team7/hrbank/domain/employee/Department.java
  src/main/java/team7/hrbank/domain/employee/EmployStatus.java
  src/main/java/team7/hrbank/domain/employee/Employee.java
  src/main/java/team7/hrbank/domain/employee/EmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/entity/Employee.java
  src/main/resources/application.yml
  src/test/java/team7/hrbank/csv/CsvTest.java
Labels: ✨ Feature

#36 [Feature] : Department 관련 기능 구현
  build.gradle
  src/main/java/team7/hrbank/HrbankApplication.java
  src/main/java/team7/hrbank/WebConfig.java
  src/main/java/team7/hrbank/domain/Department/Controller/DepartmentController.java
  src/main/java/team7/hrbank/domain/Department/Service/DepartmentService.java
  src/main/java/team7/hrbank/domain/Department/Service/DepartmentServiceImpl.java
  src/main/java/team7/hrbank/domain/Department/dto/DepartmentCreateRequest.java
  src/main/java/team7/hrbank/domain/Department/dto/DepartmentListResponse.java
  src/main/java/team7/hrbank/domain/Department/dto/DepartmentResponse.java
  src/main/java/team7/hrbank/domain/Department/dto/DepartmentUpdateRequest.java
  src/main/java/team7/hrbank/domain/Department/entity/Department.java
  src/main/java/team7/hrbank/domain/Department/exception/GlobalExceptionHandler.java
  src/main/java/team7/hrbank/domain/Department/repository/DepartmentRepository.java
  src/main/java/team7/hrbank/domain/employee/repository/CustomEmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/repository/EmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#51 [Feature]ChangeLog 수정 이력 등록 기능 생성
  src/main/java/team7/hrbank/domain/change_log/dto/ChangeLogDto.java
  src/main/java/team7/hrbank/domain/change_log/dto/CursorPageResponseChangeLogDto.java
  src/main/java/team7/hrbank/domain/change_log/repository/CustomChangeLogRepository.java
  src/main/java/team7/hrbank/domain/change_log/service/ChangeLogService.java
  src/main/java/team7/hrbank/domain/change_log/service/ChangeLogServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ Feature

#56 Feature/department #55
  src/main/java/team7/hrbank/domain/Department/entity/Department.java
  src/main/java/team7/hrbank/domain/Department/exception/GlobalExceptionHandler.java
  src/main/java/team7/hrbank/domain/department/controller/DepartmentController.java
  src/main/java/team7/hrbank/domain/department/dto/DepartmentCreateRequest.java
  src/main/java/team7/hrbank/domain/department/dto/DepartmentListResponse.java
  src/main/java/team7/hrbank/domain/department/dto/DepartmentResponse.java
  src/main/java/team7/hrbank/domain/department/dto/DepartmentUpdateRequest.java
  src/main/java/team7/hrbank/domain/department/entity/Department.java
  src/main/java/team7/hrbank/domain/department/repository/CustomDepartmentRepository.java
  src/main/java/team7/hrbank/domain/department/repository/CustomDepartmentRepositoryImpl.java
  src/main/java/team7/hrbank/domain/department/repository/DepartmentRepository.java
  src/main/java/team7/hrbank/domain/department/service/DepartmentService.java
  src/main/java/team7/hrbank/domain/department/service/DepartmentServiceImpl.java
  src/main/java/team7/hrbank/domain/employee/entity/Employee.java
Labels: ✨ Feature

#58 refactor: MapStruct 이용한 간결한 코드로 수정
  src/main/java/team7/hrbank/domain/department/controller/DepartmentController.java
  src/main/java/team7/hrbank/domain/department/dto/DepartmentMapper.java
  src/main/java/team7/hrbank/domain/department/dto/DepartmentResponseDto.java
  src/main/java/team7/hrbank/domain/department/dto/DepartmentResponseDtoList.java
  src/main/java/team7/hrbank/domain/department/service/DepartmentService.java
  src/main/java/team7/hrbank/domain/department/service/DepartmentServiceImpl.java
Labels: 🔧 Refactor

#59 [REFACTOR] Change Log 등록 기능 수정#53
  src/main/java/team7/hrbank/common/utils/IpUtil.java
  src/main/java/team7/hrbank/domain/change_log/service/ChangeLogServiceImpl.java
  src/main/java/team7/hrbank/domain/employee/controller/EmployeeController.java
  src/main/java/team7/hrbank/domain/employee/entity/Employee.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeService.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeServiceImpl.java
Labels: 🔧 Refactor

#62 [REFACTOR] Employee와 Department 연계 수정
  src/main/java/team7/hrbank/common/dto/ErrorResponse.java
  src/main/java/team7/hrbank/common/exception/ErrorCode.java
  src/main/java/team7/hrbank/common/exception/GlobalExceptionHandler.java
  src/main/java/team7/hrbank/common/exception/employee/EmployeeException.java
  src/main/java/team7/hrbank/common/extractor/EmployeeFieldExtractor.java
  src/main/java/team7/hrbank/domain/change_log/service/ChangeLogServiceImpl.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeDto.java
  src/main/java/team7/hrbank/domain/employee/entity/Employee.java
  src/main/java/team7/hrbank/domain/employee/mapper/EmployeeMapper.java
  src/main/java/team7/hrbank/domain/employee/repository/CustomEmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/repository/CustomEmployeeRepositoryImpl.java
  src/main/java/team7/hrbank/domain/employee/repository/EmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeServiceImpl.java
Labels: ✨ Feature

#61 [FEATURE] : Backup Scheduler 도입 및 실패 처리, 비동기, reader 마이그레이션
  src/main/java/team7/hrbank/common/dto/EmployeeDepartmentDto.java
  src/main/java/team7/hrbank/common/extractor/EmployeeDepartmentExtractor.java
  src/main/java/team7/hrbank/common/extractor/EmployeeFieldExtractor.java
  src/main/java/team7/hrbank/common/extractor/EmployeeRowMapper.java
  src/main/java/team7/hrbank/config/BackupBatchConfig.java
  src/main/java/team7/hrbank/domain/backup/service/BackupServiceImpl.java
  src/main/java/team7/hrbank/domain/binary/BinaryContent.java
  src/main/java/team7/hrbank/domain/change_log/service/ChangeLogServiceImpl.java
  src/main/java/team7/hrbank/domain/employee/entity/Employee.java
  src/main/java/team7/hrbank/domain/employee/repository/EmployeeRepository.java
  src/main/resources/schema.sql
Labels: ✨ Feature

#66 [REFACTOR] ChangeLog 수정
  src/main/java/team7/hrbank/common/utils/IpUtil.java
  src/main/java/team7/hrbank/domain/change_log/controller/ChangeLogController.java
  src/main/java/team7/hrbank/domain/change_log/dto/CursorPageResponseChangeLogDto.java
  src/main/java/team7/hrbank/domain/change_log/repository/CustomChangeLogRepository.java
  src/main/java/team7/hrbank/domain/change_log/repository/CustomChangeLogRepositoryImpl.java
  src/main/java/team7/hrbank/domain/change_log/service/ChangeLogService.java
  src/main/java/team7/hrbank/domain/change_log/service/ChangeLogServiceImpl.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeServiceImpl.java
  src/main/resources/schema.sql
Labels: 🔧 Refactor

#67 [FEATURE] 예외처리 추가, BaseUpdatableEntity 추가
  src/main/java/team7/hrbank/common/exception/GlobalExceptionHandler.java
  src/main/java/team7/hrbank/common/exception/employee/EmployeeException.java
  src/main/java/team7/hrbank/common/utils/ExceptionUtil.java
  src/main/java/team7/hrbank/domain/base/BaseUpdatableEntity.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeCreateRequest.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeFindRequest.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeUpdateRequest.java
  src/main/java/team7/hrbank/domain/employee/entity/Employee.java
  src/main/java/team7/hrbank/domain/employee/repository/CustomEmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/repository/CustomEmployeeRepositoryImpl.java
  src/main/java/team7/hrbank/domain/employee/repository/EmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ Feature

#73 [FEATURE] : Employee 예외처리 추가
  src/main/java/team7/hrbank/common/exception/GlobalExceptionHandler.java
  src/main/java/team7/hrbank/common/utils/EmailUtil.java
  src/main/java/team7/hrbank/domain/employee/entity/Employee.java
  src/main/java/team7/hrbank/domain/employee/repository/CustomEmployeeRepositoryImpl.java
  src/main/java/team7/hrbank/domain/employee/repository/EmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ Feature

#76 [REFACTOR] : 부서 목록 조회 페이지네이션 수정
  src/main/java/team7/hrbank/domain/department/controller/DepartmentController.java
  src/main/java/team7/hrbank/domain/department/dto/DepartmentMapper.java
  src/main/java/team7/hrbank/domain/department/dto/DepartmentResponseDto.java
  src/main/java/team7/hrbank/domain/department/dto/PageDepartmentsResponseDto.java
  src/main/java/team7/hrbank/domain/department/dto/UpdateRequest.java
  src/main/java/team7/hrbank/domain/department/dto/WithEmployeeCountResponseDto.java
  src/main/java/team7/hrbank/domain/department/repository/CustomDepartmentRepository.java
  src/main/java/team7/hrbank/domain/department/repository/CustomDepartmentRepositoryImpl.java
  src/main/java/team7/hrbank/domain/department/repository/DepartmentRepository.java
  src/main/java/team7/hrbank/domain/department/service/DepartmentService.java
  src/main/java/team7/hrbank/domain/department/service/DepartmentServiceImpl.java
  src/main/java/team7/hrbank/domain/employee/repository/EmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeServiceImpl.java
  src/main/resources/application.yml
Labels: 🔧 Refactor

#80 [Refactoring] employee create관련 로직 리팩토링
  build.gradle
  src/main/java/team7/hrbank/domain/employee/controller/EmployeeController.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeCreateRequest.java
  src/main/java/team7/hrbank/domain/employee/entity/Employee.java
  src/main/java/team7/hrbank/domain/employee/mapper/EmployeeMapper.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeServiceImpl.java
Labels: 🔧 Refactor

#79 [FIX] : Employee 문제 해결, 예외처리 수정
  src/main/java/team7/hrbank/common/exception/ErrorCode.java
  src/main/java/team7/hrbank/common/exception/GlobalExceptionHandler.java
  src/main/java/team7/hrbank/common/exception/employee/EmployeeException.java
  src/main/java/team7/hrbank/common/utils/EmailUtil.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeCreateRequest.java
  src/main/java/team7/hrbank/domain/employee/repository/CustomEmployeeRepositoryImpl.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeServiceImpl.java
Labels: 🐛 bug

#85 [Refactoring] 테스트 전 필요없는 것 삭제
  src/main/java/team7/hrbank/domain/binary/BinaryContent.java
  src/main/java/team7/hrbank/domain/binary/BinaryContentService.java
  src/main/java/team7/hrbank/domain/binary/BinaryController.java
  src/main/java/team7/hrbank/domain/binary/LocalBinaryContentStorage.java
  src/main/java/team7/hrbank/domain/binary/dto/BinaryMapper.java
Labels: 🔧 Refactor

#81 [REFACTOR] : split BackupService into Query, Process, Validation
  src/main/java/team7/hrbank/config/BackupBatchConfig.java
  src/main/java/team7/hrbank/domain/backup/service/BackupProcessService.java
  src/main/java/team7/hrbank/domain/backup/service/BackupProcessServiceImpl.java
  src/main/java/team7/hrbank/domain/backup/service/BackupQueryService.java
  src/main/java/team7/hrbank/domain/backup/service/BackupQueryServiceImpl.java
  src/main/java/team7/hrbank/domain/backup/service/BackupServiceImpl.java
  src/main/java/team7/hrbank/domain/backup/service/BackupValidationService.java
Labels: 🔧 Refactor

#88 [FIX] : 최신 develop 반영 후 일부 기능 작동하지 않는 문제 해결
  src/main/java/team7/hrbank/common/exception/GlobalExceptionHandler.java
  src/main/java/team7/hrbank/common/exception/employee/EmployeeException.java
  src/main/java/team7/hrbank/common/utils/EmailUtil.java
  src/main/java/team7/hrbank/domain/employee/controller/EmployeeController.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeCreateRequest.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeUpdateRequest.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeServiceImpl.java
  src/main/resources/application.yml
Labels: 🐛 bug

#90 [FEATURE] : Dashboard API
  src/main/java/team7/hrbank/domain/backup/service/BackupServiceImpl.java
  src/main/java/team7/hrbank/domain/change_log/service/ChangeLogServiceImpl.java
  src/main/java/team7/hrbank/domain/employee/controller/EmployeeController.java
  src/main/java/team7/hrbank/domain/employee/dashboard/DashboardController.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeDistributionDto.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeTrendDto.java
  src/main/java/team7/hrbank/domain/employee/repository/CustomEmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/repository/CustomEmployeeRepositoryImpl.java
  src/main/java/team7/hrbank/domain/employee/repository/EmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeDashboardService.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeDashboardServiceImpl.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeServiceImpl.java
Labels: ✨ Feature

#92 [REFACTOR] change log 페이지네이션 리펙토링, 예외처리, 테이블 FK삭제
  src/main/java/team7/hrbank/common/exception/GlobalExceptionHandler.java
  src/main/java/team7/hrbank/common/exception/change_log/ChangeLogNoDetectedException.java
  src/main/java/team7/hrbank/common/exception/change_log/ChangeLogNotFoundException.java
  src/main/java/team7/hrbank/domain/change_log/controller/ChangeLogController.java
  src/main/java/team7/hrbank/domain/change_log/dto/ChangeLogDto.java
  src/main/java/team7/hrbank/domain/change_log/dto/ChangeLogRequestDto.java
  src/main/java/team7/hrbank/domain/change_log/dto/CursorPageResponseChangeLogDto.java
  src/main/java/team7/hrbank/domain/change_log/entity/ChangeLog.java
  src/main/java/team7/hrbank/domain/change_log/repository/CustomChangeLogRepository.java
  src/main/java/team7/hrbank/domain/change_log/repository/CustomChangeLogRepositoryImpl.java
  src/main/java/team7/hrbank/domain/change_log/service/ChangeLogService.java
  src/main/java/team7/hrbank/domain/change_log/service/ChangeLogServiceImpl.java
  src/main/java/team7/hrbank/domain/employee/entity/Employee.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeServiceImpl.java
  src/main/resources/schema.sql
Labels: 🔧 Refactor

#94 [REFACTOR] : Employee 코드 정리
  src/main/java/team7/hrbank/common/dto/ErrorResponse.java
  src/main/java/team7/hrbank/common/dto/PageResponse.java
  src/main/java/team7/hrbank/common/exception/ErrorCode.java
  src/main/java/team7/hrbank/common/exception/GlobalExceptionHandler.java
  src/main/java/team7/hrbank/common/exception/employee/EmployeeException.java
  src/main/java/team7/hrbank/common/exception/employee/NotFoundEmployeeException.java
  src/main/java/team7/hrbank/domain/employee/controller/EmployeeController.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeCountRequest.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeCreateRequest.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeDto.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeFindRequest.java
  src/main/java/team7/hrbank/domain/employee/dto/EmployeeUpdateRequest.java
  src/main/java/team7/hrbank/domain/employee/entity/Employee.java
  src/main/java/team7/hrbank/domain/employee/entity/EmployeeStatus.java
  src/main/java/team7/hrbank/domain/employee/mapper/EmployeeMapper.java
  src/main/java/team7/hrbank/domain/employee/repository/CustomEmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/repository/CustomEmployeeRepositoryImpl.java
  src/main/java/team7/hrbank/domain/employee/repository/EmployeeRepository.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeDashboardService.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeDashboardServiceImpl.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeService.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeServiceImpl.java
Labels: 🔧 Refactor

#97 [ FIX ] 부서 생성, 수정시의 DB 미반영 문제 해결
  src/main/java/team7/hrbank/domain/department/controller/DepartmentController.java
  src/main/java/team7/hrbank/domain/department/dto/DepartmentCreateRequest.java
  src/main/java/team7/hrbank/domain/department/dto/DepartmentMapper.java
  src/main/java/team7/hrbank/domain/department/dto/DepartmentResponseDto.java
  src/main/java/team7/hrbank/domain/department/dto/DepartmentUpdateRequest.java
  src/main/java/team7/hrbank/domain/department/dto/DepartmentWithEmployeeCountResponseDto.java
  src/main/java/team7/hrbank/domain/department/dto/PageDepartmentsResponseDto.java
  src/main/java/team7/hrbank/domain/department/dto/UpdateRequest.java
  src/main/java/team7/hrbank/domain/department/dto/WithEmployeeCountResponseDto.java
  src/main/java/team7/hrbank/domain/department/entity/Department.java
  src/main/java/team7/hrbank/domain/department/repository/CustomDepartmentRepository.java
  src/main/java/team7/hrbank/domain/department/repository/CustomDepartmentRepositoryImpl.java
  src/main/java/team7/hrbank/domain/department/repository/DepartmentRepository.java
  src/main/java/team7/hrbank/domain/department/service/DepartmentService.java
  src/main/java/team7/hrbank/domain/department/service/DepartmentServiceImpl.java
Labels: 🐛 bug

#101 [REFACTOR] ChangeLog 수정 로그 기능 리펙토링
  src/main/java/team7/hrbank/domain/change_log/service/ChangeLogService.java
  src/main/java/team7/hrbank/domain/change_log/service/ChangeLogServiceImpl.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeServiceImpl.java
Labels: 🔧 Refactor

#105 [FEATURE] Trend 통계 batch 작업으로 사전 생성
  src/main/java/team7/hrbank/common/batch/DailyTrendFullBatch.java
  src/main/java/team7/hrbank/common/batch/MonthlyTrendFullBatch.java
  src/main/java/team7/hrbank/common/batch/QuaterlyTrendFullBatch.java
  src/main/java/team7/hrbank/common/batch/WeeklyTrendFullBatch.java
  src/main/java/team7/hrbank/common/batch/YearlyTrendFullBatch.java
  src/main/java/team7/hrbank/common/batch/rowmapper/ChangeLogRowMapper.java
  src/main/java/team7/hrbank/common/dto/StatisticChangeLogDto.java
  src/main/java/team7/hrbank/common/scheduler/TrendScheduler.java
  src/main/java/team7/hrbank/domain/change_log/entity/ChangeLog.java
  src/main/java/team7/hrbank/domain/change_log/repository/ChangeLogRepository.java
  src/main/java/team7/hrbank/domain/change_log/service/ChangeLogServiceImpl.java
  src/main/java/team7/hrbank/domain/department/entity/Department.java
  src/main/java/team7/hrbank/domain/department/repository/CustomDepartmentRepositoryImpl.java
  src/main/java/team7/hrbank/domain/employee/dashboard/DashboardController.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeDashboardService.java
  src/main/java/team7/hrbank/domain/employee/service/EmployeeDashboardServiceImpl.java
  src/main/java/team7/hrbank/domain/emplyee_statistic/EmployeeStatistic.java
  src/main/java/team7/hrbank/domain/emplyee_statistic/EmployeeStatisticRepository.java
  src/main/java/team7/hrbank/domain/emplyee_statistic/EmployeeStatisticType.java
  src/main/java/team7/hrbank/domain/emplyee_statistic/FullTrendStatisticGenerator.java
  src/main/java/team7/hrbank/domain/emplyee_statistic/StatController.java
  src/main/java/team7/hrbank/domain/emplyee_statistic/TrendUpdater.java
  src/main/resources/schema.sql
Labels: ✨ Feature

#110 [FIX] : 사원번호 정렬 로직 수정
  src/main/java/team7/hrbank/common/exception/GlobalExceptionHandler.java
  src/main/java/team7/hrbank/domain/employee/repository/CustomEmployeeRepositoryImpl.java
  src/test/java/team7/hrbank/employee/EmployeeTest.java
Labels: 🐛 bug

#112 [REFACTOR] 페이지네이션 성능개선
  src/main/java/team7/hrbank/domain/department/repository/CustomDepartmentRepositoryImpl.java
Labels: 🔧 Refactor

#113 [FIX] : ChangeLog IP주소 정렬 수정
  src/main/java/team7/hrbank/domain/change_log/repository/CustomChangeLogRepositoryImpl.java
  src/main/java/team7/hrbank/domain/change_log/service/ChangeLogServiceImpl.java
Labels: 🐛 bug

#117 [FIX] 부서명 검증 / 부서 목록 조회시 내림차순에서 중복조회되는 문제 해결
  src/main/java/team7/hrbank/domain/department/repository/CustomDepartmentRepositoryImpl.java
  src/main/java/team7/hrbank/domain/department/service/DepartmentServiceImpl.java
Labels: 🐛 bug
